import "EngineControl.idl";
import "DevTools/SourcesFileTabItem.idl";
import "DevTools/SourcesTabCallStackTabItem.idl";

namespace MEraEmuWin.DevTools {
    [default_interface]
    runtimeclass MainPage : Windows.UI.Xaml.Controls.Page {
        MainPage();

        IVector<SourcesFileTabItem> SourcesFileTabsItemList{ get; };
        IVector<SourcesTabCallStackTabItem> SourcesTabCallStackTabItemsList{ get; };

        void SetConnectedEngineControl(MEraEmuWin.EngineControl engine);
    };
}
