namespace MEraEmuWin.DevTools {
    [bindable]
    [default_interface]
    runtimeclass SourcesTabCallStackTabItem {
        SourcesTabCallStackTabItem();

        String FuncName;
        String FileName;
        UInt32 LineNumber;
        UInt32 ColumnNumber;
        UInt32 SrcSpanStart;
        UInt32 SrcSpanLen;
        UInt32 IpChunk;
        UInt32 IpOffset;
        UInt32 RetIpChunk;
        UInt32 RetIpOffset;
        Boolean IsCurrent;
    };
}
