namespace MEraEmuWin.DevTools {
    [bindable]
    [default_interface]
    runtimeclass SourcesFileTabItem {
        SourcesFileTabItem();

        String FileName;
        String FullPath;
        Boolean IsInited;
    };
}
