namespace MEraEmuWin {
    [bindable]
    [default_interface]
    runtimeclass AppSettingsVM {
        AppSettingsVM();

        AppSettingsVM DeepClone();

        // General
        Boolean EnableParallelLoading;
        Boolean EnableJIT;

        // Game
        UInt32 SaveDataCount;
        Boolean EnableAutoSave;
    };
}
