namespace MEraEmuWin {
    [bindable]
    [default_interface]
    runtimeclass AppSettingsVM {
        AppSettingsVM();

        AppSettingsVM DeepClone();

        // General
        Boolean ReadResourcesDir;
        Boolean ReadFontsDir;
        Boolean ReadSoundDir;
        Boolean EnableParallelLoading;
        Boolean EnableJIT;
        Boolean EnableEngineControlOnError;

        // Game
        UInt32 SaveDataCount;
        Boolean EnableAutoSave;

        // Display
        Boolean AutoDetectGameUIScale;
        Double GameUIScale;
        String GameDefaultFontName;
        Double GameFontSize;
        Double GameLineHeight;
        Windows.UI.Color GameBackgroundColor;
        Windows.UI.Color GameForegroundColor;
        Windows.UI.Color GameHighlightColor;
        UInt32 GamePrintCCountPerLine;
        UInt32 GamePrintCCharCount;
        Boolean EnableFontSmoothing;
        Boolean EnablePixelSnapping;
        Boolean EnableHtmlRendering;
        Boolean EnableGdiCompatRender;
        Boolean EnableHardwareAcceleration;
        Boolean DebugShowLayoutBounds;
    };
}
