import "AppSettingsVM.idl";

namespace MEraEmuWin {
    runtimeclass EngineUnhandledExceptionEventArgs {
        Windows.Foundation.HResult Code{ get; };
        String Message{ get; };
    };

    [default_interface]
    runtimeclass EngineControl : Windows.UI.Xaml.Controls.UserControl {
        EngineControl();

        void ReturnToTitle();
        void ApplySettings(MEraEmuWin.AppSettingsVM settings);

        Boolean IsStarted{ get; };
        Boolean IsDevToolsOpen;
        Double AudioVolume;

        event Windows.Foundation.EventHandler<EngineUnhandledExceptionEventArgs> UnhandledException;

        static Windows.UI.Xaml.DependencyProperty EngineForeColorProperty{ get; };
        Windows.UI.Color EngineForeColor;
        static Windows.UI.Xaml.DependencyProperty EngineBackColorProperty{ get; };
        Windows.UI.Color EngineBackColor;
        static Windows.UI.Xaml.DependencyProperty EngineTitleProperty{ get; };
        String EngineTitle;

        // XAML helpers
        Windows.UI.Xaml.Media.SolidColorBrush ColorToBrush(Windows.UI.Color value);
    }
}
